### PR TITLE
external-snapshotter constantly retrying CreateSnapshot calls on error w/o backoff

### LINKED ISSUE #778: Retry interval of failed volume snapshot creation or deletion does not double after each failure: v6.0.1
**What happened**:

Created VolumeSnapshot but the request failed  due to authorisation issue in storage provider. In logs, I could see frequent calls to `CreateSnapshot` method.  Ad per doc, it should double after each failure but logs doesn't show that behaviour. 

**What you expected to happen**:
retry interval of failed volume snapshot creation or deletion should double after each failure

**How to reproduce it**:

Create a  negative test scenario where VolumeSnapshot Creation fails and observe csi-snapshotter sidecar logs.

**Anything else we need to know?**:

```
cat csi-snapshotter.log | grep "GRPC call: /csi.v1.Controller/CreateSnapshot"
I1103 09:23:10.412875       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:12.306660       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:12.477653       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:12.785050       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:12.943098       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:13.124844       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:13.700102       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:14.300774       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:14.904655       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:15.504961       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:16.101649       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:16.704480       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:17.303818       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:17.904957       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:18.524977       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:19.100899       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:19.701028       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:20.302357       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:20.903176       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:21.502685       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:22.101407       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:22.701141       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:23.306374       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:23.902031       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:24.546378       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:25.104353       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:25.706340       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:26.304882       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:26.902224       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:27.500703       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:28.100920       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:28.705816       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
```

`csi-snapshotter` has errors logged

```
I1103 09:23:10.412875       1 connection.go:183] GRPC call: /csi.v1.Controller/CreateSnapshot
I1103 09:23:10.412881       1 connection.go:184] GRPC request: {"name":"snapshot-b9eb23d0-cd0d-47e9-a73f-da6d2132bde1","source_volume_id":"r014-41301bc5-7acf-4013-aaae-386ae5cbd5f4"}
I1103 09:23:10.426415       1 snapshot_controller_base.go:162] enqueued "snapcontent-b9eb23d0-cd0d-47e9-a73f-da6d2132bde1" for sync
I1103 09:23:12.279782       1 connection.go:186] GRPC response: {}
I1103 09:23:12.279876       1 connection.go:187] GRPC error: rpc error: code = Internal desc = {RequestID: 556ec084-4b68-4bd7-bd9f-fcc5f44bccaf , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:SnapshotSpaceOrderFailed, Type:ProvisioningFailed, Description:Snapshot space order failed for the given volume ID, BackendError:Trace Code:556ec084-4b68-4bd7-bd9f-fcc5f44bccaf, The user is not authorized Please check Check access permissions and try again., RC:500}, Action: Please check 'BackendError' tag for more details}
I1103 09:23:12.279895       1 snapshot_controller.go:324] createSnapshotWrapper: CreateSnapshot for content snapcontent-b9eb23d0-cd0d-47e9-a73f-da6d2132bde1 returned error: rpc error: code = Internal desc = {RequestID: 556ec084-4b68-4bd7-bd9f-fcc5f44bccaf , Code: InternalError, Description: Internal error occurred%!(EXTRA string=creation), BackendError: {Code:SnapshotSpaceOrderFailed, Type:ProvisioningFailed, Description:Snapshot space order failed for the given volume ID, BackendError:Trace Code:556ec084-4b68-4bd7-bd9f-fcc5f44bccaf, The user is not authorized Please check Check access permissions and try again., RC:500}, Action: Please check 'BackendError' tag for more details}
```

External-Snapshotter version : v6.0.1

Related PR for reference : https://github.com/kubernetes-csi/external-snapshotter/pull/651

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`): 1.25
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by sameshai**
Signed-off-by: Sameer Shaikh [sameer.shaikh@ibm.com](mailto:sameer.shaikh@ibm.com)

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
external-snapshotter constantly retrying CreateSnapshot calls on error w/o backoff

**Which issue(s) this PR fixes**:

Fixes #778

**Special notes for your reviewer**:
@xing-yang @zhucan @pwschuurman 

ResourceEventHandlerFuncs is a implementation of ResourceEventHandler, whose method OnUpdate has the following documentation:

[external-snapshotter/vendor/k8s.io/client-go/tools/cache/controller.go](https://github.com/kubernetes-csi/external-snapshotter/blob/e746d0717a32109d8c57cb76a70b299ec849f54d/vendor/k8s.io/client-go/tools/cache/controller.go#L203-L208)

```
 //  * OnUpdate is called when an object is modified. Note that oldObj is the 
 //      last known state of the object-- it is possible that several changes 
 //      were combined together, so you can't use this to see every single 
 //      change. OnUpdate is also called when a re-list happens, and it will 
 //      get called even if nothing changed. This is useful for periodically 
 //      evaluating or syncing something. 
```
Considering the object is modified more than once during the workflow (for example when there is an error), it might be possible that oldObj doesn't have the annotation set anymore and the check in line 111 doesn't really work.

 Hence we don't really need to worry about this annotation. Can we not just rely on error object ? If there is failure lets not re-queue it 

[external-snapshotter/pkg/sidecar-controller/snapshot_controller_base.go](https://github.com/kubernetes-csi/external-snapshotter/blob/e746d0717a32109d8c57cb76a70b299ec849f54d/pkg/sidecar-controller/snapshot_controller_base.go#L111)

I will attach more logs and scenarios that proves that we cant rely on this old and new object annotations rather we should just rely if error then dont requeue

**Does this PR introduce a user-facing change?**:

```release-note
Fix a problem in CSI snapshotter sidecar that constantly retries CreateSnapshot call on error without exponential backoff. Comparing old and new object is not working as expected
```

### CODE REVIEW

**Comment by sameshai** [comment]
Attaching the logs with more logging for error scenario which randomly updates the oldobject and newobject for annotations which suggest lets not rely on these updates and annotations.

 
[csi-snapshotter-error-logs.zip](https://github.com/kubernetes-csi/external-snapshotter/files/11892157/csi-snapshotter-error-logs.zip)


Attaching logs for success scenario where the CreateSnashpot will be re-queued until readyToUse is true


[csi-snapshotter-success.zip](https://github.com/kubernetes-csi/external-snapshotter/files/11892550/csi-snapshotter-success.zip)

File: pkg/sidecar-controller/snapshot_controller_base.go [hunk 1]
```diff
@@ -124,12 +123,7 @@ func NewCSISnapshotSideCarController(
 				// So we are skipping the re-queue here to avoid CreateSnapshot being called without exponential backoff.
 				newSnapContent := newObj.(*crdv1.VolumeSnapshotContent)
 				if newSnapContent.Status != nil && newSnapContent.Status.Error != nil {
-					oldSnapContent := oldObj.(*crdv1.VolumeSnapshotContent)
```
Comment (xing-yang) [inline pkg/sidecar-controller/snapshot_controller_base.go:127]: Can you update the comments accordingly.

Comment (sameshai) [reply pkg/sidecar-controller/snapshot_controller_base.go:127]: Done @xing-yang let me know if the comments are ok

File: pkg/sidecar-controller/snapshot_controller_base.go [hunk 2]
```diff
@@ -121,15 +120,12 @@ func NewCSISnapshotSideCarController(
 				// VolumeSnapshotContent.
 				// This will trigger a VolumeSnapshotContent update and it will cause the obj to be re-queued immediately
 				// and CSI CreateSnapshot will be called again without exponential backoff.
+				// Considering the object is modified more than once during the workflow we are not relying on the annoations of oldobj and newobj.
+				// We will just check if newobj status has error and avoid re-queue.
```
Comment (xing-yang) [inline pkg/sidecar-controller/snapshot_controller_base.go:124]: // Considering the object is modified more than once during the workflow we are not relying on the
// "AnnVolumeSnapshotBeingCreated" annotation. Instead we will just check if newobj status has error
// and avoid the immediate re-queue. This allows the retry to happen with exponential backoff.
