### PR TITLE
fix: group snapshot not taken on conflict

### LINKED ISSUE #1357: Group snapshot not taken on conflict v2
This is continuation of https://github.com/kubernetes-csi/external-snapshotter/issues/1280
[The patch](https://github.com/kubernetes-csi/external-snapshotter/pull/1354) did not help, now the e2e test fail just a bit later.

Test results from a downstream e2e job:
* [overview](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/openshift-csi-external-snapshotter-191-ci-4.21-e2e-aws-ovn-techpreview/1999407913239580672)
* [snapshot-controller logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/openshift-csi-external-snapshotter-191-ci-4.21-e2e-aws-ovn-techpreview/1999407913239580672/artifacts/e2e-aws-ovn-techpreview-8/gather-extra/artifacts/pods/openshift-cluster-storage-operator_csi-snapshot-controller-f66668547-249gr_snapshot-controller.log)

The test panicked [here](https://github.com/openshift/kubernetes/blob/fc8194c3c027bcccc0f8088fd37a27a2b3aef8fe/test/e2e/storage/testsuites/volume_group_snapshottable.go#L196):
```
k8s.io/kubernetes/test/e2e/storage/testsuites.(*VolumeGroupSnapshottableTestSuite).DefineTests.func1.1.5({0x7efc10eca568, 0xc0032afa40})
	k8s.io/kubernetes/test/e2e/storage/testsuites/volume_group_snapshottable.go:196 +0x1054

fail [runtime/iface.go:275]: Test Panicked: interface conversion: interface {} is nil, not string
fail [runtime/iface.go:275]: Test Panicked
```

I.e. the snapshot controller declared a GroupSnapshot `readyToUse=True`, but it did not file `status.volumeSnapshotInfoList[]`. Which is a bug, this must never happen.

The real root cause of https://github.com/kubernetes-csi/external-snapshotter/issues/1280 seems to be deeper than simple error checks.

### PR DESCRIPTION
**Pull request by Phaow**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
- Follow up of patch https://github.com/kubernetes-csi/external-snapshotter/pull/1354, since the origin patch does not use the createdVolumeSnapshotContent object returned from the API for patch actions caused `status.volumeSnapshotInfoList[]` incorrect.

**Which issue(s) this PR fixes**:

Fixes #1357

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Phaow** [comment]
Hi @jsafrane , could you help review when you get a chance? Thank you!

File: pkg/common-controller/groupsnapshot_controller_helper.go [hunk 1]
```diff
@@ -530,194 +566,277 @@ func (ctrl *csiSnapshotCommonController) createSnapshotsForGroupSnapshotContent(
...
+	volumeSnapshotContent *crdv1.VolumeSnapshotContent,
+) (*crdv1.VolumeSnapshotContent, error) {
+	createdVolumeSnapshotContent, err := ctrl.clientset.SnapshotV1().VolumeSnapshotContents().Create(ctx, volumeSnapshotContent, metav1.CreateOptions{})
 
+	if apierrs.IsAlreadyExists(err) {
+		createdVolumeSnapshotContent, err = ctrl.clientset.
+			SnapshotV1().
+			VolumeSnapshotContents().
+			Get(ctx, volumeSnapshotContent.Name, metav1.GetOptions{})
 	}
```
Comment (jsafrane) [inline pkg/common-controller/groupsnapshot_controller_helper.go:737]: I'd like to point out this is the actual bugfix: when the `snapshotContent` (or `snapshot`) already exists, `Get()` it from the API server and use it to compute all `Patch()` calls below.

Everything else is just refactoring a huge `createSnapshotsForGroupSnapshotContent` into smaller chunks.

Comment (Phaow) [reply pkg/common-controller/groupsnapshot_controller_helper.go:737]: Thanks for the clarification!
