### PR TITLE
Call dynamic VS content creation unconditionally

### LINKED ISSUE #333: Snapshot controller cannot recover from missing volume snapshot class error
In the current implementation of the snapshot controller, in checkAndUpdateSnapshotClass()
if a missing volume snapshot class is detected, an error status is stamped on the volume snapshot object. 
Periodic sync, does not clear the error status. Side effect of this is that, even if the volume snapshot class is detected in the subsequent resyncs, syncUnreadySnapshot() never triggers the snapshot content creation object. Because following condition never evaluates to true (snapshot.Status == nil || snapshot.Status.Error == nil || isControllerUpdateFailError(snapshot.Status.Error)), and the volume snapshot workflow is stuck.

Possible fixes:
1. Do not update any error status on the volume object i.e skip calling updateSnapshotErrorStatusWithEvent() from checkAndUpdateSnapshotClass(), and only log an error message. The state machine would fail gracefully while creating a VS content object.

2. Do not  update the error status on volume object, but generate an event. (this needs additional changes to ensure that only 1 event is generated, maybe stamp an annotation of missing VSC on the volume object, before generating event)

3. Update the error status as it is done today, but when we detect a VSC in subsequent resync clear the error status (this needs to ensure we check the error msg reason and clear only the VSC missing error status)

4. Update error status for missing VSC as it is done today, but handle this VSC missing error in syncUnreadySnapshot() and proceed with VS content creation. VS content creation would fail gracefully if the VSC is still missing.

### PR DESCRIPTION
**Pull request by saikat-royc**
Irrespective of any error on the Volume Snapshot
object, initiate dynamic VolumeSnapshotContent object
creation. If any required parameters are not found, (e.g. missing
VS class), the VS content object creation would fail gracefully.

**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
Recover from intermittent  errors in VolumeSnapshot object

**Which issue(s) this PR fixes**:

Fixes #333 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Recover from intermittent errors in VolumeSnapshot object
```

### CODE REVIEW

**Comment by xing-yang** [comment]
Can you add a few test cases:
1. Initial snapshot.Status = nil
2. Initial snapshot.Status.Error = nil
3. Initial snapshot.Status.Error != nil
Initial Content is nil for all 3 cases.  New content should be created.

**Comment by saikat-royc** [comment]
Added test cases as mentioned above.

File: pkg/common-controller/snapshot_update_test.go [hunk 1]
```diff
@@ -510,6 +510,48 @@ func TestSync(t *testing.T) {
...
+			errors:            noerrors,
+			expectSuccess:     true,
+			test:              testNewSnapshotContentCreation,
+		},
+		{
+			// Snapshot status with nil error, no initial content, new content should be created.
+			name:              "8-2 - Snapshot status with nil error, no initial snapshot content, new content should be created",
+			initialContents:   nocontents,
+			expectedContents:  withContentAnnotations(newContentArrayNoStatus("snapcontent-snapuid8-2", "snapuid8-2", "snap8-2", "sid8-2", validSecretClass, "", "pv-handle8-2", deletionPolicy, nil, nil, false, false), map[string]string{utils.AnnDeletionSecretRefName: "secret", utils.AnnDeletionSecretRefNamespace: "default"}),
+			initialSnapshots:  newSnapshotArray("snap8-2", "snapuid8-2", "claim8-2", "", validSecretClass, "", nil, nil, nil, nil, true, false, nil),
```
Comment (xing-yang) [inline pkg/common-controller/snapshot_update_test.go:532]: This test case looks exactly the same as 8-1?
Can you set snapshot status to be not nil, but just with Error set to nil?  boundSnapshotContentName can be set based on the content created and ReadyToUse set to False.

File: pkg/common-controller/snapshot_update_test.go [hunk 2]
```diff
@@ -510,6 +510,48 @@ func TestSync(t *testing.T) {
...
+			errors:            noerrors,
+			expectSuccess:     true,
+			test:              testNewSnapshotContentCreation,
+		},
+		{
+			// Snapshot status with error, no initial content, new content should be created, snapshot error should be cleared.
+			name:              "8-3 - Snapshot status with error, no initial content, new content should be created, snapshot error should be cleared",
+			initialContents:   nocontents,
+			expectedContents:  withContentAnnotations(newContentArrayNoStatus("snapcontent-snapuid8-3", "snapuid8-3", "snap8-3", "sid8-3", validSecretClass, "", "pv-handle8-3", deletionPolicy, nil, nil, false, false), map[string]string{utils.AnnDeletionSecretRefName: "secret", utils.AnnDeletionSecretRefNamespace: "default"}),
+			initialSnapshots:  newSnapshotArray("snap8-3", "snapuid8-3", "claim8-3", "", validSecretClass, "", nil, nil, nil, nil, true, false, nil),
```
Comment (xing-yang) [inline pkg/common-controller/snapshot_update_test.go:546]: This test case looks exactly the same as 8-1 and 8-2.
Can you set the err field of newSnapshotArray in initialSnapshots? https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/framework_test.go#L937
https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/framework_test.go#L1071

Comment (saikat-royc) [reply pkg/common-controller/snapshot_update_test.go]: my bad missed pushing some local changes
