### PR TITLE
Fix the race between PVC finalizer and snapshot finalizer removal

### LINKED ISSUE #349: VolumeSnapshot cannot be deleted
Kubernetes version: v1.18.5
CSI snapshotter version: v2.1.1

ouptput of `kubectl get volumesnapshot`
```log
NAME                              READYTOUSE   SOURCEPVC          SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS               SNAPSHOTCONTENT                                    CREATIONTIME   AGE
test-snapshot-dynamic-provision   false        quobyte-csi-test                                         quobyte-csi-snapshotclass   snapcontent-e5af5c7e-89bd-42a4-bd5d-e00f205f243c                  14h
```
events from `kubectl describe volumesnapshot`
```log
Events:
  Type     Reason                         Age   From                 Message
  ----     ------                         ----  ----                 -------
  Warning  SnapshotContentCreationFailed  54m   snapshot-controller  Failed to create snapshot content with error snapshot controller failed to update quobyte-csi-test on API server: cannot add finalizer on claim because it is being deleted
```

logs from `snapshot-controller`
```log
I0811 09:58:46.942919       1 snapshot_controller.go:893] Keeping PVC default/quobyte-csi-test, it is used by snapshot default/test-snapshot-dynamic-provision
I0811 09:58:46.942935       1 snapshot_controller.go:229] PVC default/quobyte-csi-test is being used by snapshot default/test-snapshot-dynamic-provision as source
I0811 09:58:46.942945       1 snapshot_controller.go:609] createSnapshotContent: Creating content for snapshot default/test-snapshot-dynamic-provision through the plugin ...
E0811 09:58:46.942953       1 snapshot_controller.go:838] cannot add finalizer on claim [quobyte-csi-test] for snapshot [test-snapshot-dynamic-provision]: claim is being deleted
E0811 09:58:46.942957       1 snapshot_controller.go:615] createSnapshotContent failed to add finalizer for source of snapshot snapshot controller failed to update quobyte-csi-test on API server: cannot add finalizer on claim because it is being deleted
E0811 09:58:46.942973       1 snapshot_controller_base.go:378] could not sync volume "default/test-snapshot-dynamic-provision": snapshot controller failed to update quobyte-csi-test on API server: cannot add finalizer on claim because it is being deleted
I0811 09:59:46.850093       1 snapshot_controller.go:893] Keeping PVC default/quobyte-csi-test, it is used by snapshot default/test-snapshot-dynamic-provision
I0811 09:59:46.850107       1 snapshot_controller.go:229] PVC default/quobyte-csi-test is being used by snapshot default/test-snapshot-dynamic-provision as source
I0811 09:59:46.850113       1 snapshot_controller.go:609] createSnapshotContent: Creating content for snapshot default/test-snapshot-dynamic-provision through the plugin ...
E0811 09:59:46.850117       1 snapshot_controller.go:838] cannot add finalizer on claim [quobyte-csi-test] for snapshot [test-snapshot-dynamic-provision]: claim is being deleted
E0811 09:59:46.850120       1 snapshot_controller.go:615] createSnapshotContent failed to add finalizer for source of snapshot snapshot controller failed to update quobyte-csi-test on API server: cannot add finalizer on claim because it is being deleted
E0811 09:59:46.850127       1 snapshot_controller_base.go:378] could not sync volume "default/test-snapshot-dynamic-provision": snapshot controller failed to update quobyte-csi-test on API server: cannot add finalizer on claim because it is being deleted
```

PVC status
```
NAME               STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
quobyte-csi-test   Terminating   pvc-39577f6c-c107-4417-9da8-0cd559441d76   1Gi        RWO            quobyte-csi    15h
````

snapshotter sidecar does not have any relevant logs.

`Workaround:` Setting finalizers to null as below on the PVC on which the snapshot is created, removed both PVC and volume snapshot.
```
# Set finalizers on the PVC to null
kubectl get pvc <PVC> -o=json | jq '.metadata.finalizers = null' | kubectl apply -f -
```

### PR DESCRIPTION
**Pull request by xing-yang**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #349 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Fix a problem deleting the PVC finalizer and snapshot finalizer.
```

### CODE REVIEW

**Comment by huffmanca** [comment]
I've tested this, and it addresses the issue that I was mentioning in https://github.com/kubernetes-csi/external-snapshotter/pull/354 . I am able to delete a VolumeSnapshot that has a source of a non-CSI PVC.

**Comment by chrishenzie** [comment]
Just tested this but was unable to delete the PVC nor VolumeSnapshot. [This was the manifest that was used](https://gist.github.com/chrishenzie/e5aa2c2e5f12d7b0bfba80181e7f61a0), which tries creates a VolumeSnapshot at the same time the PVC is created.

**Comment by humblec** [comment]
@xing-yang are we targetting this for 2.2?

**Comment by chrishenzie** [comment]
@xing-yang Just tested using the same manifest linked above. All resources deleted successfully without any issues. Thank you!

**Comment by xing-yang** [comment]
@chrishenzie Thank you for testing this!

File: pkg/common-controller/snapshot_controller.go [hunk 1]
```diff
@@ -170,17 +170,14 @@ func (ctrl *csiSnapshotCommonController) syncSnapshot(snapshot *crdv1.VolumeSnap
...
 		klog.Errorf("error check and remove PVC finalizer for snapshot [%s]: %v", snapshot.Name, err)
 		// Log an event and keep the original error from checkandRemovePVCFinalizer
 		ctrl.eventRecorder.Event(snapshot, v1.EventTypeWarning, "ErrorPVCFinalizer", "Error check and remove PVC Finalizer for VolumeSnapshot")
 	}
 
-	// Proceed with snapshot deletion only if snapshot is not in the middled of being
-	// created from a PVC with a finalizer. This is to ensure that the PVC finalizer
-	// can be removed even if a delete snapshot request is received before create
-	// snapshot has completed.
-	if snapshot.ObjectMeta.DeletionTimestamp != nil && !ctrl.isPVCwithFinalizerInUseByCurrentSnapshot(snapshot) {
```
Comment (ggriffiths) [inline pkg/common-controller/snapshot_controller.go:183]: nit: can delete the function `isPVCwithFinalizerInUseByCurrentSnapshot` since it's not being used anymore

Comment (xing-yang) [reply pkg/common-controller/snapshot_controller.go:183]: You are right.  Deleted.

**Comment by xing-yang** [comment]
@ggriffiths Addressed your comments.  PTAL.  Thanks.

File: pkg/common-controller/snapshot_controller.go [hunk 2]
```diff
@@ -1303,6 +1285,16 @@ func (ctrl *csiSnapshotCommonController) removeSnapshotFinalizer(snapshot *crdv1
 		return nil
 	}
 
+	// If we are here, it means we are going to remove finalizers from the snapshot so that the snapshot can be deleted.
+	// We need to check if there is still PVC finalizer that needs to be removed before removing the snapshot finalizers.
+	// Once snapshot is deleted, there won't be any snapshot update event that can trigger the PVC finalizer removal.
+	if err := ctrl.checkandRemovePVCFinalizer(snapshot, true); err != nil {
```
Comment (yuxiangqian) [inline pkg/common-controller/snapshot_controller.go:1291]: I am not sure this is the best place to put the fix.
checkandRemoveSnapshotFinalizersAndCheckandDeleteContent, which is the caller of this function, has quite some returning points, i.e., this:
https://github.com/kubernetes-csi/external-snapshotter/blob/521502eef991ae09ecd8590cfa67397c7c7da973/pkg/common-controller/snapshot_controller.go#L258

if any of those points is hit, it will still cause the PVC not deletable.

File: pkg/common-controller/snapshot_controller.go [hunk 3]
```diff
@@ -170,17 +170,14 @@ func (ctrl *csiSnapshotCommonController) syncSnapshot(snapshot *crdv1.VolumeSnap
 	klog.V(5).Infof("syncSnapshot [%s]: check if we should remove finalizer on snapshot PVC source and remove it if we can", utils.SnapshotKey(snapshot))
 
 	// Check if we should remove finalizer on PVC and remove it if we can.
-	if err := ctrl.checkandRemovePVCFinalizer(snapshot); err != nil {
+	if err := ctrl.checkandRemovePVCFinalizer(snapshot, false); err != nil {
```
Comment (yuxiangqian) [inline pkg/common-controller/snapshot_controller.go:173]: IMHO, checkandRemovePVCFinalizer *can* take the responsibility to handle "snapshot.ObjectMeta.DeletionTimestamp != nil" case,
and the bool flag can be saved?

Comment (xing-yang) [reply pkg/common-controller/snapshot_controller.go:185]: I think it is safer to have this bool flag passed in.  Even when "snapshot.ObjectMeta.DeletionTimestamp != nil", it is possible that snapshot is also used as a source for another PVC.  In that case, we still want to keep PVC finalizer on the snapshot's source if snapshot is not ready yet.

**Comment by ibadullaev-inc4** [comment]
Hi.
I have the same problem.

**Comment by xing-yang** [comment]
What version of external-snapshotter are you using?

**Comment by xing-yang** [comment]
Are you trying to modify VolumeSnapshot name?  This field is immutable.

```
E0617 01:58:22.574735       1 snapshot_controller_base.go:399] could not sync snapshot "geth/data-gethu-0-20220617000103": snapshot controller failed to update data-gethu-0-20220617000103 on API server: snapshot controller failed to update data-gethu-0 on API server: PersistentVolumeClaim "data-gethu-0" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	... // 4 identical fields
  	StorageClassName: &"ebs-sc",
  	VolumeMode:       &"Filesystem",
  	DataSource: &core.TypedLocalObjectReference{
  		APIGroup: &"snapshot.storage.k8s.io",
  		Kind:     "VolumeSnapshot",
- 		Name:     "data-gethu-0-20220617005748",
+ 		Name:     "data-gethu-0-20220609235015",
  	},
  	DataSourceRef: nil,
  }
```

**Comment by ibadullaev-inc4** [comment]
> 09235015

No I try to delete volumesnapshot.

1) List PVC in geth namespace:
```
[nariman@notebook bnb]$ kubectl -n geth get pvc
NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-gethu-0   Bound    pvc-1ca62d5d-f661-4f6c-b095-37a3d148c911   800Gi      RWO            ebs-sc         7d21h
```
2) Describe pvc  **NOTE** on the field DataSource.Name
```
[nariman@notebook bnb]$ kubectl -n geth describe pvc data-gethu-0
Name:          data-gethu-0
Namespace:     geth
StorageClass:  ebs-sc
Status:        Bound
Volume:        pvc-1ca62d5d-f661-4f6c-b095-37a3d148c911
Labels:        app=gethu
Annotations:   policies.kyverno.io/last-applied-patches: set-name-latest-snapshot.mutate-pvc.kyverno.io: replaced /spec/dataSource/name
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-10-0-1-41.us-east-2.compute.internal
Finalizers:    [kubernetes.io/pvc-protection snapshot.storage.kubernetes.io/pvc-as-source-protection]
Capacity:      800Gi
Access Modes:  RWO
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      data-gethu-0-20220609235015
Used By:     gethu-0
Events:      <none>

```

3) List volumesnapshots
```
[nariman@notebook bnb]$ kubectl -n geth get volumesnapshots.snapshot.storage.k8s.io 
NAME                          READYTOUSE   SOURCEPVC      SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS       SNAPSHOTCONTENT                                    CREATIONTIME   AGE
data-gethu-0-20220617005748   true         data-gethu-0                           800Gi         aws-block-storage   snapcontent-8ebc315e-1690-408c-b322-e640d9f3d75c   20h            20h

```

4) try to delete: result stuck 
```
[nariman@notebook bnb]$ kubectl -n geth delete volumesnapshots.snapshot.storage.k8s.io data-gethu-0-20220617005748
volumesnapshot.snapshot.storage.k8s.io "data-gethu-0-20220617005748" deleted
```

**LOG**
[log.txt](https://github.com/kubernetes-csi/external-snapshotter/files/8931492/log.txt)
